PROVIDER_LIST = {
    "austintx": "Austin Water (Austin, TX)",
    "breckenridge": "Town of Breckenbridge Water (Breckenbridge, CO)",
    "greeley": "City of Greeley (Greeley, CO)",
    "gwresources": "Global Water Resources",
    "lmwd": "Laguna Madre Water District (Port Isabel, TX)",
    "lvmwd": "Las Virgenes Municipal Water District (Calabasas, CA)",
    "ogden": "Ogden City Water Utility (Ogden, UT)",
    "santacruz": "Soquel Creek Water District (Santa Cruz, CA)",
    "thornton": "City of Thornton Water, (Thornton, CO)",
    "valleycentermwd": "Valley Center Municipal Water District (Valley Center, CA)",
    "waco": "City of Waco (Waco, TX)",
    "waterlooia": "Waterloo Water Works (Waterloo, IA)",
    "yonkersny": "Yonkers Water (Yonkers, NY)",
    "zephyrhillsfl": "Zephyr Hills Water Utility (Zephyr Hills, FL)",
}
